{{- if (and .Values.auditLog.enabled .Values.auditLog.dynamicBackend.enabled) }}
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: {{ template "falco.fullname" .}}
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      url: http://{{ required "A valid .Values.auditLog.clusterIP entry required" .Values.auditLog.clusterIP }}:{{ .Values.falco.webserver.listenPort }}{{ .Values.falco.webserver.k8sAuditEndpoint }}
{{- end }}
